[package]
authors = ["Ballerina"]
distribution = "2201.12.0"
keywords = ["AI/Vector Database", "Cost/Freemium", "Vendor/Pinecone", "Area/AI & Machine Learning", "Type/Vector Store", "Type/Util", "Name/Pinecone Vector Store"]
license = ["Apache-2.0"]
name = "ai.pinecone"
org = "ballerinax"
repository = "https://github.com/ballerina-platform/module-ballerinax-ai.pinecone"
icon = "icon.png"
version = "@toml.version@"

[platform.java21]
graalvmCompatible = true
